Meteo:
  type: object
  config:
    description: "Meteo types"
    fields:
      minTemperature:
        type: "Int"
        description: "le min de meteo"
      maxTemperature:
        type: "Int"
        description: "le max de meteo"
      ville:
        type: "String"
        description: "le ville"
      textMeteo:
        type: "String"
        description: "la description de meteo"