Query:
  type: object
  config:
    description: "Main query"
    fields:
      meteo:
        type: "Meteo"
        args:
          ville:
            description: "get meteo"
            type: "String"
        resolve: "@=resolver('Meteo', [args])"
